<div align="center">

**LAPORAN PRAKTIKUM**

**STRUKTUR DATA**

**“TIPE DATA DAN VARIABEL”**

**Disusun Oleh :**

**M. Abdurrauf**

**2611532032**

**Dosen Pengampu:**

**Dr. Ir WAHYUDI, ST., MT.**

**Asisten Praktikum:**

**Sherly Sukmadira**

<br>

 <img src="logo_unand.png" width="200">

<br>

**FAKULTAS TEKNOLOGI INFORMASI**

**DEPARTEMEN INFORMATIKA**

**UNIVERSITAS ANDALAS**

**2026**

</div>

## KATA PENGANTAR

Puji syukur saya panjatkan ke hadirat Tuhan Yang Maha Esa atas segala rahmat, nikmat, dan karunia-Nya sehingga saya dapat menyelesaikan laporan praktikum ini dengan baik. Laporan ini disusun sebagai salah satu bentuk dokumentasi dan pertanggungjawaban atas kegiatan praktikum yang telah dilaksanakan pada mata kuliah Praktikum Algoritma dan Pemrograman, khususnya pada pertemuan ke-2 dengan materi Pengenalan Tipe Data dan Variabel dalam Bahasa Pemrograman Python.

Praktikum ini bertujuan untuk memberikan pemahaman mengenai konsep dasar dalam bahasa pemrograman Python, terutama mengenai berbagai jenis tipe data dan penggunaan variabel. Dalam pemrograman, tipe data dan variabel merupakan bagian yang sangat penting karena digunakan untuk menyimpan, mengolah, serta mengatur berbagai informasi yang diperlukan dalam sebuah program. Melalui kegiatan praktikum ini, saya dapat mempelajari secara langsung bagaimana cara mengenali berbagai macam tipe data, menentukan nilai suatu variabel, serta memahami perbedaan karakteristik dari setiap tipe data yang digunakan dalam bahasa pemrograman Python.

Selain itu, kegiatan praktikum ini juga memberikan pengalaman dalam menerapkan materi yang telah dipelajari secara langsung melalui penulisan dan pengujian kode program. Dengan adanya praktikum, pemahaman terhadap materi tidak hanya diperoleh secara teori, tetapi juga melalui proses praktik secara langsung. Hal tersebut membantu saya untuk lebih memahami bagaimana sebuah program bekerja serta bagaimana konsep-konsep dasar pemrograman dapat diterapkan dalam menyelesaikan suatu permasalahan sederhana.

Saya berharap melalui praktikum ini, pemahaman mengenai dasar-dasar pemrograman Python dapat semakin berkembang dan menjadi bekal untuk mempelajari materi pemrograman yang lebih kompleks pada pertemuan-pertemuan berikutnya. Selain itu, praktikum ini juga diharapkan dapat meningkatkan kemampuan dalam berpikir logis, sistematis, dan kritis dalam menyusun sebuah program.

Saya menyadari bahwa dalam penyusunan laporan praktikum ini masih terdapat berbagai kekurangan dan kesalahan, baik dari segi isi, penyusunan, maupun penyampaian materi. Oleh karena itu, kritik dan saran yang membangun sangat saya harapkan sebagai bahan evaluasi dan perbaikan untuk penyusunan laporan maupun kegiatan pembelajaran di masa yang akan datang.

Akhir kata, saya mengucapkan terima kasih kepada dosen, asisten praktikum, serta semua pihak yang telah memberikan arahan dan membantu selama proses pelaksanaan praktikum hingga penyusunan laporan ini. Semoga laporan praktikum ini dapat memberikan manfaat, menambah wawasan, serta menjadi salah satu sumber pembelajaran dalam memahami dasar-dasar Algoritma dan Pemrograman menggunakan bahasa Python.
Padang, 2026

Alif Maulana Kesi

---
# BAB I
# PENDAHULUAN

## 1.1 Latar Belakang
Perkembangan teknologi informasi yang semakin pesat menjadikan kemampuan dalam memahami pemrograman sebagai salah satu keterampilan yang penting untuk dipelajari, khususnya bagi mahasiswa di bidang Informatika. Pemrograman merupakan proses memberikan instruksi kepada komputer untuk menyelesaikan suatu permasalahan atau menjalankan tugas tertentu melalui bahasa pemrograman.

Salah satu bahasa pemrograman yang banyak digunakan saat ini adalah Python. Python memiliki sintaks yang sederhana dan mudah dipahami sehingga cocok digunakan untuk mempelajari konsep dasar pemrograman. Dalam mempelajari bahasa pemrograman Python, terdapat beberapa konsep dasar yang perlu dipahami, salah satunya adalah variabel dan tipe data.

Variabel digunakan untuk menyimpan suatu nilai atau informasi yang dapat digunakan dan diolah dalam sebuah program. Sementara itu, tipe data digunakan untuk menentukan jenis nilai yang disimpan dalam variabel, seperti bilangan bulat, bilangan desimal, teks, maupun nilai logika. Pemahaman mengenai variabel dan tipe data sangat penting karena keduanya menjadi dasar dalam proses pengolahan data pada sebuah program.

Oleh karena itu, praktikum ini dilaksanakan agar mahasiswa dapat memahami konsep variabel dan berbagai jenis tipe data dalam bahasa pemrograman Python, baik secara teori maupun melalui praktik langsung. Dengan adanya kegiatan praktikum, mahasiswa diharapkan mampu mengenali, menggunakan, dan mengelompokkan berbagai jenis data serta menerapkannya dalam pembuatan program sederhana.
## 1.2 Tujuan
1.  Memahami konsep dasar bahasa pemrograman Python.
2.	Mengenal pengertian dan fungsi variabel dalam pemrograman.
3.	Mengetahui berbagai jenis tipe data yang terdapat dalam bahasa Python.
4.	Mampu menentukan dan mengidentifikasi tipe data dari suatu nilai atau variabel.
5.	Mampu menerapkan penggunaan variabel dan tipe data dalam pembuatan program sederhana menggunakan Python.
6.	Melatih kemampuan mahasiswa dalam memahami dan menulis kode program secara logis dan sistematis.

## 1.3 Manfaat
1.	Mahasiswa dapat memahami dasar-dasar pemrograman menggunakan bahasa Python.
2.	Mahasiswa dapat mengenal dan memahami penggunaan variabel dalam sebuah program.
3.	Mahasiswa dapat membedakan berbagai jenis tipe data dalam bahasa Python.
4.	Mahasiswa memperoleh pengalaman praktik secara langsung dalam menulis dan menjalankan program.
5.	Mahasiswa dapat meningkatkan kemampuan berpikir logis dan sistematis dalam menyelesaikan permasalahan melalui pemrograman.
6.	Praktikum ini dapat menjadi dasar dan bekal untuk mempelajari materi pemrograman yang lebih lanjut dan lebih kompleks.

---
# BAB II
# PEMBAHASAN

## 2.1 Dasar Teori

1. Algoritma dan Pemrograman

Algoritma merupakan serangkaian langkah-langkah yang disusun secara logis, terstruktur, dan sistematis untuk menyelesaikan suatu permasalahan. Algoritma menjadi dasar dalam pembuatan sebuah program karena menentukan bagaimana suatu masalah dapat diselesaikan melalui langkah-langkah tertentu. Pemrograman merupakan proses menerapkan algoritma ke dalam bahasa yang dapat dipahami dan dijalankan oleh komputer. Melalui pemrograman, seseorang dapat memberikan instruksi kepada komputer untuk melakukan tugas tertentu sesuai dengan tujuan yang telah ditentukan.

2. Bahasa Pemrograman Python

Python merupakan salah satu bahasa pemrograman tingkat tinggi yang banyak digunakan dalam berbagai bidang. Python dikenal sebagai bahasa pemrograman yang memiliki sintaks sederhana, mudah dibaca, dan mudah dipahami, sehingga cocok digunakan untuk mempelajari dasar-dasar pemrograman. Python dapat digunakan dalam berbagai bidang, seperti pengembangan aplikasi, website, pengolahan data, kecerdasan buatan, otomatisasi, dan berbagai kebutuhan teknologi lainnya. Kemudahan dalam penggunaan serta perkembangan yang luas menjadikan Python sebagai salah satu bahasa pemrograman yang banyak dipelajari.

3. Variabel

Variabel merupakan nama atau tempat yang digunakan untuk menyimpan suatu nilai atau data di dalam program. Data yang disimpan dalam variabel dapat digunakan kembali dan diolah sesuai dengan kebutuhan program. Dalam bahasa pemrograman Python, variabel digunakan untuk mempermudah proses penyimpanan dan pengolahan data. Nilai yang terdapat dalam sebuah variabel dapat berubah sesuai dengan instruksi yang diberikan dalam program.

4. Tipe Data

Tipe data merupakan jenis atau kategori dari nilai yang disimpan dalam sebuah variabel. Setiap tipe data memiliki karakteristik yang berbeda dan digunakan sesuai dengan jenis informasi yang akan diolah. Dalam bahasa Python, terdapat beberapa tipe data dasar yang sering digunakan, yaitu Integer, Float, String, dan Boolean. Integer digunakan untuk bilangan bulat, Float digunakan untuk bilangan desimal, String digunakan untuk data berupa teks atau karakter, sedangkan Boolean digunakan untuk nilai logika yang memiliki dua kemungkinan, yaitu benar atau salah.
Pemahaman mengenai tipe data sangat penting karena jenis data yang digunakan akan memengaruhi proses pengolahan data dalam sebuah program.


5. Hubungan Variabel dan Tipe Data

Variabel dan tipe data merupakan dua konsep dasar yang saling berkaitan dalam pemrograman. Variabel berfungsi sebagai tempat untuk menyimpan informasi, sedangkan tipe data menunjukkan jenis dari informasi atau nilai yang disimpan tersebut. Dengan memahami penggunaan variabel dan tipe data, seorang programmer dapat mengelola data dengan lebih baik serta menentukan proses yang tepat dalam pembuatan sebuah program.



6. Pentingnya Memahami Variabel dan Tipe Data

Pemahaman mengenai variabel dan tipe data merupakan salah satu dasar penting dalam mempelajari bahasa pemrograman. Kedua konsep tersebut digunakan dalam hampir seluruh proses pembuatan program, mulai dari penyimpanan data hingga pengolahan informasi. Dengan memahami materi ini, mahasiswa dapat lebih mudah mempelajari konsep pemrograman selanjutnya, seperti operator, percabangan, perulangan, fungsi, dan struktur data. Oleh karena itu, penguasaan terhadap variabel dan tipe data menjadi langkah awal yang penting dalam mempelajari pemrograman menggunakan bahasa Python.

## 2.2 Kode Program

### 2.2.1 Program Boolean_2611532032


In [ ]:
# Nama variabel dengan tipe data Boolean 
# Deklarasi variabel dengan tipe data Boolean  
is_lulus_2032 = True
is_cumlaude_2032 = True

# Menggunakan Boolean 
nilai_2032 = 85 
batas_lulus_2032 = 75 

# Menentukan nilai Boolean dari kondisi
status_kelulusan = nilai_2032 >= batas_lulus_2032 # Hasilnya akan True

print("=== Check Kelulusan===")
print("NIlai: ", nilai_2032)
print("Apakah Lulus?:", status_kelulusan)

=== Check Kelulusan===
NIlai:  85
Apakah Lulus?: True


**Penjelasan :**
1. Bagian 1 sampai 2 berfungsi untuk membuat variabel Boolean is_lulus_2032 dengan nilai True dan is_cumlaide_2032 dengan nilai False.
2. Bagian 3 sampai 4 berfungsi untuk menyimpan nilai mahasiswa dan batas nilai kelulusan ke dalam variabel.
3. Bagian 6 membandingkan nilai dengan batas lulus,hasilnya disimpan sebagai Boolean.
4. Bagian 8 sampai 10 berfungsi untuk menampilkan judul, nilai mahasiswa, dan hasil status kelulusan.

### 2.2.1 Program Input_2611532032

In [ ]:
# Buat  program untuk menghitung luas persegi panjang 
# Nama variabel ditambah 4 digit nim terakhir contoh: panjang_2032
# Progaram ini menggunakan fungsi  input() untuk mememinta pengguna
# memasukkan nilai panjang dan lebar persegi panjang.
# Nilai yang dimasukkan akan dikonversi menjadi tipe data integer
panjang_2032 =  input('Masukkan nilai panjang: ')
lebar_2032 = input('Masukkan nilai lebar: ')
luas_2032 = int(panjang_2032) * int(lebar_2032)
print("luas =", luas_2032)

luas = 50


**Penjelasan :**
1. input() meminta pengguna mengetik nilai panjang dan lebar (hasilnya berupa teks/string).
2. int(...) mengubah teks itu jadi angka bulat.
3. luas_2032 = int(panjang_2032) * int(lebar_2032) → hitung luas dengan mengalikan keduanya.
4. print() menampilkan hasilnya.

### 2.2.1 Program Konstanta_2611532032

In [ ]:
# Program ini menggunakan konstanta untuk menghitung luas lingkaran
# nama variabel ditambah 4 digit nim terakhir contoh: jari_2032

from typing import Final
PI: Final = 3.14
print("pi: %f" % (PI))
jari_2032 = float(input('Masukkan nilai jari-jari: '))
luas_2032 = PI * jari_2032 * jari_2032
print("Luas lingkaran dengan jari-jari %.2f adalah %.2f" % (jari_2032, luas_2032))

pi: 3.140000
Luas lingkaran dengan jari-jari 10.00 adalah 314.00


**Penjelasan :**
1. PI: Final = 3.14 — bikin konstanta PI (nilainya 3.14, tidak boleh diubah lagi, ditandai dengan Final).
2. print("pi: %f" % (PI)) — nampilin nilai PI.
3. jari_2032 = float(input(...)) — minta user masukkan jari-jari lingkaran, diubah jadi angka desimal.
4. luas_2032 = PI * jari_2032 * jari_2032 — rumus luas lingkaran (π × r × r).
5. print(...) — tampilkan hasil luasnya, dibulatkan 2 angka di belakang koma.

### 2.2.1 Program Numerik_2611532032

In [ ]:
# nama variabel ditambah 4 digit terakhir NIM contoh:a_2032
# create a variabel with numeric type value
a_2032=100
print("The type of variabel having value", a_2032," is ", type(a_2032))

#create a variabel with float value
b_2032=10.2345
print("The type of variabel having value", b_2032," is ", type(b_2032))

#create a variabel with complex value
c_2032=100+3j
print("The type of having value", c_2032, " is ", type(c_2032))

The type of variabel having value 100  is  <class 'int'>
The type of variabel having value 10.2345  is  <class 'float'>
The type of having value (100+3j)  is  <class 'complex'>


**Penjelasan :**
1. Baris 1–2 — membuat variabel a_2032 bertipe integer (bilangan bulat), nilainya 100. Lalu type() dipakai untuk menampilkan jenis tipe datanya.
2. Baris 3–4 — membuat variabel b_2032 bertipe float (bilangan desimal), nilainya 10.2345, lalu ditampilkan tipenya.
3. Baris 5–6 — membuat variabel c_2032 bertipe complex (bilangan kompleks, ada bagian imajiner 3j), lalu ditampilkan tipenya.

### 2.2.1 Program String_2611532032

In [ ]:
#nama variabel ditambah 4 digit nim terakhir contoh : M.Abdurrauf_2032
#diganti programnya dan data masing2
nama_2032 = "M.Abdurrauf"
jenis_kelamin_2032 = 'L' 
alamat_2032 = """ 
   Kota Padang
   Kec. Padang selatan
   Komp. Jondul Rawang
"""
agama = 'islam'
print("Nama saya adalah: ", nama_2032)
print("Jenis kelamin saya adalah: ", jenis_kelamin_2032)
print("Alamat saya adalah: ", alamat_2032)
print("Agama saya adalah : ", agama_2032)

**Penjelasan :**
1. nama_2032 — variabel string biasa (pakai tanda kutip dua " ") untuk menyimpan nama.
2. jenis_kelamin_2032 — variabel string pakai tanda kutip satu ' ', isinya cuma satu karakter 'L'.
3. alamat_2032 — variabel string dengan tanda kutip tiga """ """, dipakai untuk teks yang lebih dari satu baris (multi-line string).
4. agama_2032 — variabel string biasa lagi, pakai kutip satu.
5. Bagian print() di bawahnya cuma menampilkan masing-masing data (nama, jenis kelamin, alamat, agama) ke layar.

"## Tugas Praktikum\n",
    
**Soal :**
Sistem Biodata dan Validasi Kelulusan Praktikan

 Rancang sebuah program konsol sederhana yang mencatat data identitas praktikan baru dan melakukan verifikasi status kelulusan awal praktikum secara otomatis dengan syarat
 1. Nama berkas `Tugas2_2611532032.py` dan seluruh variabel diakhiri dengan 4 digit terakhir NIM (`_2032`).
 2. Terapkan konstanta batas kelulusan menggunakan modul `typing.Final`.
 3. Terapkan tipe data String & Char (untuk nama, jenis kelamin, dan multiline string untuk alamat).
 4. Terapkan tipe data Numerik & Type Casting (`int` untuk umur, `float` untuk skor, dan `complex` untuk token identifikasi).
5. Evaluasi kelulusan secara dinamis menjadi tipe data Boolean dan tampilkan seluruh tipe data ke layar menggunakan fungsi bawaan `type()`"

In [ ]:
# Kode program tugas "Tugas2_2611532032.py"

from typing import Final

# Konstanta batas kelulusan
BATAS_LULUS: Final = 75.0

print("=== SISTEM REGISTRASI PRAKTIKAN ALPRO 2026 ===")
nama_2032 = input("Masukkan Nama Mahasiswa\t\t: ")
jenis_kelamin_2032 = input("Masukkan Jenis Kelamin (L/P)\t: ")
umur_2032 = int(input("Masukkan Umur\t\t\t: "))
skor_tes_2032 = float(input("Masukkan Skor Tes Awal\t\t: "))

# Deklarasi alamat secara multiline
alamat_2032 = """Kebun Kopi, Kec. Jambi Selatan, Kota Jambi"""

# Token identifikasi menggunakan bilangan kompleks
token_2032 = 100+3j

# Evaluasi status kelulusan
status_lulus_2032 = skor_tes_2032 >= BATAS_LULUS

print("\n=== DATA PRAKTIKAN & HASIL PEMERIKSAAN ===")
print("Nama Mahasiswa\t:", nama_2032, "| Tipe:", type(nama_2032))
print("Jenis Kelamin\t:", jenis_kelamin_2032, "| Tipe:", type(jenis_kelamin_2032))
print("Alamat Domisili\t:\n" + alamat_2032, "\n| Tipe:", type(alamat_2032))
print("Umur\t\t:", umur_2032, "tahun | Tipe:", type(umur_2032))
print("Skor Tes Awal\t:", skor_tes_2032, "| Tipe:", type(skor_tes_2032))
print("ID Token Sinyal\t:", token_2032, "| Tipe:", type(token_2032))

print("\n=== STATUS KELULUSAN PRAKTIKUM ===")
print("Batas Minimum Nilai:", BATAS_LULUS)
print("Apakah Dinyatakan Lulus?:", status_lulus_2032, "| Tipe:", type(status_lulus_2032))

=== SISTEM REGISTRASI PRAKTIKAN ALPRO 2026 ===


 "**Penjelasan :**\n",
Program tugas `tugas2_2611532032.py` adalah implementasi sistem biodata dan verifikasi kelulusan terpadu.
1. Program mengunci nilai ketetapan skor (`BATAS_LULUS = 75.0`) menggunakan dekorator konstan dari modul `typing.Final`.
2. Pengumpulan identitas memanfaatkan `input()` yang dikonversi bentuknya secara paksa (type casting) ke tipe numerik yang tepat: tipe integer `int()` untuk `umur_2032` dan tipe float desimal `float()` untuk `skor_tes_2032`.
3. Variabel `alamat_2032` memanfaatkan tanda kutip tiga (multiline string) agar struktur baris alamat tetap utuh berderet ke bawah, sementara variabel `token_2032` diisi nilai bilangan kompleks `100+3j`.
4. Evaluasi komparasi logika `skor_tes_2032 >= BATAS_LULUS` dilakukan untuk memeriksa apakah nilai pengguna melewati batas, lalu hasil kebenarannya disimpan sebagai `True` atau `False` (boolean) pada variabel `status_lulus_2032`.
5. Terakhir, variabel yang telah terisi dicetak ke layar dan dibersandingkan dengan fungsi bawaan `type()` guna membuktikan bahwa jenis tipe datanya valid sesuai dengan instruksi."


---
# BAB III
# KESIMPULAN

Algoritma menjadi dasar logika sebelum suatu masalah diterjemahkan ke dalam bahasa pemrograman, dan Python dipilih karena sintaksnya yang sederhana dan mudah dipahami. Dari praktik program konstanta, numerik, dan string yang telah dibuat, terlihat bahwa variabel berperan sebagai tempat penyimpanan nilai, sedangkan tipe data (integer, float, complex, string, hingga konstanta menggunakan Final) menentukan bagaimana nilai tersebut diperlakukan dan diolah oleh program. Kesalahan dalam memahami tipe data dapat menyebabkan program berjalan tidak sesuai harapan, misalnya saat melakukan operasi matematis atau menggabungkan teks. Oleh karena itu, penguasaan konsep variabel dan tipe data menjadi fondasi penting sebelum mempelajari materi pemrograman yang lebih lanjut seperti operator, percabangan, dan perulangan.

---
## DAFTAR PUSTAKA
1. Kadir, A. (2019). Dasar Logika Pemrograman Komputer. Jakarta: Elex Media Komputindo.
2. Downey, A. B. (2015). Think Python: How to Think Like a Computer Scientist (2nd ed.). O'Reilly Media.
3. Python Software Foundation. (2024). The Python Tutorial. Diakses dari https://docs.python.org/3/tutorial/
4. Sutabri, T. (2012). Konsep Dasar Ilmu Sistem Informasi. Yogyakarta: Andi Offset.
5. Munir, R. (2016). Algoritma dan Pemrograman dalam Bahasa Pascal dan C. Bandung: Informatika.